# Generated by Django 3.1.5 on 2021-03-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_auto_20210319_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemcurso',
            old_name='imoveis',
            new_name='curso',
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
